#!/usr/bin/python3

def raise_exception():
    raise Exception("Exception has been raised")
